# Site settings
title: 海阔凭鱼跃,天高任鸟飞
header-img: "img/green.jpg"
tagline: "cn"  
description: ""  
baseurl: ""
url: ""  

# About/contact
owner: 
  name: " Vincent"
  bio: ""

# Data
gavatar: ""
favicon: img/favicon.png

douban_username:  
twitter_username: absolute8511 

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Vincent"
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : 
  disqus :
      short_name : 

# Links to include in footer navigation
